# Generated by Django 5.0.3 on 2024-03-14 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledTasks",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("day", models.CharField(max_length=15)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("deadline", models.DateTimeField()),
                ("emergency_status", models.CharField(max_length=500)),
            ],
        ),
    ]
