# Generated by Django 5.0.3 on 2024-03-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_scheduledtasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="day",
            field=models.CharField(default="unscheduled", max_length=15),
        ),
    ]
