# Generated by Django 5.0.6 on 2024-06-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_scheduledtasks_id_alter_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('color', models.CharField(max_length=10)),
                ('x_position', models.IntegerField(default=0)),
                ('y_position', models.IntegerField(default=0)),
            ],
        ),
    ]
